### ISSUE TITLE
Some problems about two-stage data synthesis

### ISSUE THREAD

**Issue by zhoucz97** [bin123apple/AutoCoder#13]
Hi, thanks for good job. I would like to ask the author a few questions about the data synthesis:

1. How much data distilled from the teacher model was used to initialize a student model?
2. How much data does the student model use for self-learning?
3. Each iteration generates 2k data entries mentioned in the paper. How many iterations will the performance of the student model no longer improve?

**Comment by bin123apple** [comment]
Hey, thanks for asking!

For 1: One thing I need to clarify, based on our pipeline inside the paper, even if the student model enter into the self-learning stage, there is also some possibility for it to get back to the teaching stage. Thus I did not statistic the exact the data amount to reach the "critical point".  However based on my memory, about 1/5 the data are generated by self-learning stage.

For 2: As I said in Q1, about 1/5 of the data. (May not be very accurate)

For 3: During the data synthesis loop, the "performance of the model" is actually NOT measured by a fixed benchmark. It is measured by using the 10% of the generated data as the test dataset.  We only compared it with the gpt's result. Thus, it is hard to say when the performance will not be improved as it is measured by different test dataset each time.

**Comment by zhoucz97** [comment]
> Hey, thanks for asking!
> 
> For 1: One thing I need to clarify, based on our pipeline inside the paper, even if the student model enter into the self-learning stage, there is also some possibility for it to get back to the teaching stage. Thus I did not statistic the exact the data amount to reach the "critical point". However based on my memory, about 1/5 the data are generated by self-learning stage.
> 
> For 2: As I said in Q1, about 1/5 of the data. (May not be very accurate)
> 
> For 3: During the data synthesis loop, the "performance of the model" is actually NOT measured by a fixed benchmark. It is measured by using the 10% of the generated data as the test dataset. We only compared it with the gpt's result. Thus, it is hard to say when the performance will not be improved as it is measured by different test dataset each time.

Thanks for your response!
