### ISSUE TITLE
Support datagen on any arbirtrary github repo 

### ISSUE THREAD

**Issue by jonathanpv** [bin123apple/AutoCoder#7]
This is great, is there any plans to support debugging / dataset creation from any repository?

I imagine coding models for each repository would be beneficial however the "code interpretor" or the engine that runs the code must support more than just python. And from my perspective may be difficult and only support languages that implement jupyter notebooks? Is that a limitation you forsee for being able to gen a compiler/compute backed dataset for any arbitrary gh repo? 

For example

https://github.com/vectordotdev/vector

**Comment by bin123apple** [comment]
Code models itself primarily focus on fundamental coding ability. To accomplish more complex coding tasks, we need to equip this brain (model) with limbs such as independent terminals, browsers, storage space, etc. Then, we can connect them with prompts to form an Agent or a Multi-Agent system. 

We are currently working on a related project. Thank you for your attention.
